FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:12-stretch-run

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
                    pigpio \
                    python-pigpio

CMD [ "usr\bin\pigpiod" ]