FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:12-stretch-run

RUN apt-get update && \
    apt-get install -yq --no-install-recommends \
                    pigpio \
                    python-pigpio && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy and Start app
ADD start.sh /start.sh
CMD ["bash", "/start.sh"]